=== RitaOm/xsltShop/src/main/webapp/data/products.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/products"
	xmlns:tns="http://www.example.org/products" elementFormDefault="qualified">

	<element name="products">
		<complexType>
			<sequence>
				<element name="category" type="tns:Category" minOccurs="1"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<complexType name="Category">
		<sequence>
			<element name="subcategory" type="tns:Subcategory" maxOccurs="unbounded" />
		</sequence>
		<attribute name="category_name" type="string" use="required" />
	</complexType>

	<complexType name="Subcategory">
		<sequence>
			<element name="good" type="tns:Good" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
		<attribute name="subcategory_name" type="string" use="required" />
	</complexType>

	<complexType name="Good">
		<sequence>
			<element name="producer" type="string" />
			<element name="model">
				<simpleType>
					<restriction base="string">
						<pattern value="[a-zA-Z]{2}[\d]{3}" />
					</restriction>
				</simpleType>
			</element>
			<element name="date">
				<simpleType>
					<restriction base="string">
						<pattern value="(0?[1-9]|[12]\d|3[01])\-(0?[1-9]|[1][012])\-\d{4}" />
					</restriction>
				</simpleType>
			</element>
			<element name="color" type="string" />
			<choice>
				<element name="price" type="float" />
				<element name="not_in_stock" type="string" />
			</choice>
		</sequence>
	</complexType>

</schema>

=== RitaOm/xsltShop/src/main/webapp/data/products.xml
<?xml version="1.0" encoding="UTF-8"?>
<products xmlns:def="http://www.example.org/products"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/products products.xsd ">
	<category category_name="Clothing">
		<subcategory subcategory_name="pants">
			<good>
				<producer>German</producer>
				<model>RT234</model>
				<date>01-12-2014</date>
				<color>WHITE</color>
				<price>125600</price>
			</good>
			<good>
				<producer>Belarus</producer>
				<model>HG890</model>
				<date>02-12-2014</date>
				<color>RED</color>
				<not_in_stock />
			</good>
			<good>
				<producer>Belarus</producer>
				<model>YY123</model>
				<date>12-12-2013</date>
				<color>BLACK</color>
				<price>134600</price>
			</good>
		</subcategory>
		<subcategory subcategory_name="blouse">
			<good>
				<producer>Korea</producer>
				<model>RT234</model>
				<date>21-11-2014</date>
				<color>BLOND</color>
				<price>1240</price>
			</good>
			<good>
				<producer>Russia</producer>
				<model>HQ225</model>
				<date>04-12-2014</date>
				<color>WHITE</color>
				<not_in_stock />
			</good>
			<good>
				<producer>USA</producer>
				<model>BN777</model>
				<date>21-11-2014</date>
				<color>LIME</color>
				<not_in_stock />
			</good>
			<good>
				<producer>Poland</producer>
				<model>KL555</model>
				<date>04-12-2014</date>
				<color>YELLOW</color>
				<price>3250</price>
			</good>
		</subcategory>
		<subcategory subcategory_name="jacket">
			<good>
				<producer>Korea</producer>
				<model>FG000</model>
				<date>21-11-2014</date>
				<color>GREY</color>
				<price>45</price>
			</good>
			<good>
				<producer>Belarus</producer>
				<model>JJ908</model>
				<date>04-12-2014</date>
				<color>YELLOW</color>
				<price>23</price>
			</good>
			<good>
				<producer>China</producer>
				<model>NH674</model>
				<date>21-11-2014</date>
				<color>PINK</color>
				<price>30</price>
			</good>
			<good>
				<producer>Russia</producer>
				<model>WQ900</model>
				<date>04-12-2014</date>
				<color>ORANGE</color>
				<not_in_stock />
			</good>
		</subcategory>
		<subcategory subcategory_name="socks">
			<good>
				<producer>Korea</producer>
				<model>HH505</model>
				<date>21-11-2014</date>
				<color>VINOUS</color>
				<price>11.4</price>
			</good>
			<good>
				<producer>Korea</producer>
				<model>SY657</model>
				<date>04-12-2014</date>
				<color>BRONZE</color>
				<price>13.9</price>
			</good>
		</subcategory>
	</category>

	<category category_name="Music">
		<subcategory subcategory_name="tools">
			<good>
				<producer>German</producer>
				<model>RT234</model>
				<date>01-12-2014</date>
				<color>WHITE</color>
				<not_in_stock />
			</good>
			<good>
				<producer>Belarus</producer>
				<model>HG890</model>
				<date>02-12-2014</date>
				<color>RED</color>
				<price>12</price>
			</good>
			<good>
				<producer>Belarus</producer>
				<model>YY123</model>
				<date>12-12-2013</date>
				<color>BLACK</color>
				<price>10</price>
			</good>
		</subcategory>
		<subcategory subcategory_name="records">
			<good>
				<producer>Korea</producer>
				<model>RT234</model>
				<date>21-11-2014</date>
				<color>BLOND</color>
				<not_in_stock />
			</good>
			<good>
				<producer>Russia</producer>
				<model>HQ225</model>
				<date>04-12-2014</date>
				<color>WHITE</color>
				<not_in_stock />
			</good>
			<good>
				<producer>USA</producer>
				<model>BN777</model>
				<date>21-11-2014</date>
				<color>LIME</color>
				<price>150</price>
			</good>
			<good>
				<producer>Poland</producer>
				<model>KL555</model>
				<date>04-12-2014</date>
				<color>YELLOW</color>
				<price>76</price>
			</good>
		</subcategory>
		<subcategory subcategory_name="headphones">
			<good>
				<producer>Korea</producer>
				<model>HH504</model>
				<date>21-11-2014</date>
				<color>VINOUS</color>
				<price>11.4</price>
			</good>
			<good>
				<producer>Korea</producer>
				<model>SY657</model>
				<date>04-12-2014</date>
				<color>BRONZE</color>
				<not_in_stock />
			</good>
		</subcategory>
		<subcategory subcategory_name="players">
			<good>
				<producer>Korea</producer>
				<model>HH504</model>
				<date>21-11-2014</date>
				<color>VINOUS</color>
				<not_in_stock />
			</good>
			<good>
				<producer>Korea</producer>
				<model>SY657</model>
				<date>04-12-2014</date>
				<color>BRONZE</color>
				<price>13.9</price>
			</good>
			<good>
				<producer>India</producer>
				<model>In909</model>
				<date>21-01-2014</date>
				<color>BLUE</color>
				<not_in_stock />
			</good>
		</subcategory>
	</category>

	<category category_name="Toys">
		<subcategory subcategory_name="soft">
			<good>
				<producer>German</producer>
				<model>RT234</model>
				<date>01-12-2014</date>
				<color>WHITE</color>
				<not_in_stock />
			</good>
			<good>
				<producer>Belarus</producer>
				<model>HG890</model>
				<date>02-12-2014</date>
				<color>RED</color>
				<price>12</price>
			</good>
			<good>
				<producer>Belarus</producer>
				<model>YY123</model>
				<date>12-12-2013</date>
				<color>BLACK</color>
				<price>10</price>
			</good>
		</subcategory>
		<subcategory subcategory_name="electronic">
			<good>
				<producer>Korea</producer>
				<model>RT234</model>
				<date>21-11-2014</date>
				<color>BLOND</color>
				<price>150</price>
			</good>
			<good>
				<producer>Russia</producer>
				<model>HQ225</model>
				<date>04-12-2014</date>
				<color>WHITE</color>
				<price>76</price>
			</good>
			<good>
				<producer>USA</producer>
				<model>BN777</model>
				<date>21-11-2014</date>
				<color>LIME</color>
				<not_in_stock />
			</good>
			<good>
				<producer>Poland</producer>
				<model>KL555</model>
				<date>04-12-2014</date>
				<color>YELLOW</color>
				<price>120</price>
			</good>
		</subcategory>
		<subcategory subcategory_name="puzzle">
			<good>
				<producer>Korea</producer>
				<model>FG000</model>
				<date>21-11-2014</date>
				<color>GREY</color>
				<price>45</price>
			</good>
			<good>
				<producer>Belarus</producer>
				<model>JJ908</model>
				<date>04-12-2014</date>
				<color>YELLOW</color>
				<price>23</price>
			</good>
			<good>
				<producer>China</producer>
				<model>NH674</model>
				<date>21-11-2014</date>
				<color>PINK</color>
				<price>30</price>
			</good>
			<good>
				<producer>Russia</producer>
				<model>WQ900</model>
				<date>04-12-2014</date>
				<color>ORANGE</color>
				<price>46</price>
			</good>
		</subcategory>
		<subcategory subcategory_name="rubber">
			<good>
				<producer>Korea</producer>
				<model>HH504</model>
				<date>21-11-2014</date>
				<color>VINOUS</color>
				<price>11.4</price>
			</good>
			<good>
				<producer>Korea</producer>
				<model>SY657</model>
				<date>04-12-2014</date>
				<color>BRONZE</color>
				<price>13.9</price>
			</good>
		</subcategory>
	</category>


	<category category_name="Books">
		<subcategory subcategory_name="classic">
			<good>
				<producer>Korea</producer>
				<model>HH504</model>
				<date>21-11-2014</date>
				<color>VINOUS</color>
				<price>11.4</price>
			</good>
			<good>
				<producer>Korea</producer>
				<model>SY657</model>
				<date>04-12-2014</date>
				<color>BRONZE</color>
				<price>13.9</price>
			</good>
		</subcategory>
		<subcategory subcategory_name="modern">
			<good>
				<producer>Belarus</producer>
				<model>HH504</model>
				<date>21-11-2014</date>
				<color>VINOUS</color>
				<price>11.4</price>
			</good>
			<good>
				<producer>Korea</producer>
				<model>SY657</model>
				<date>04-12-2014</date>
				<color>BRONZE</color>
				<price>13.9</price>
			</good>
			<good>
				<producer>China</producer>
				<model>HY785</model>
				<date>20-01-2014</date>
				<color>RED</color>
				<not_in_stock />
			</good>
			<good>
				<producer>Belarus</producer>
				<model>BB878</model>
				<date>21-12-2014</date>
				<color>RED</color>
				<not_in_stock />
			</good>
		</subcategory>
		<subcategory subcategory_name="research">
			<good>
				<producer>Korea</producer>
				<model>HH507</model>
				<date>21-11-2015</date>
				<color>VINOUS</color>
				<price>11.4</price>
			</good>
			<good>
				<producer>Korea</producer>
				<model>SY657</model>
				<date>04-12-2014</date>
				<color>BRONZE</color>
				<price>13.9</price>
			</good>
			<good>
				<producer>Turkey</producer>
				<model>TY790</model>
				<date>21-01-2015</date>
				<color>WHITE</color>
				<price>140.00</price>
			</good>
			<good>
				<producer>Turkey</producer>
				<model>MU890</model>
				<date>22-01-2015</date>
				<color>White</color>
				<not_in_stock />
			</good>
			<good>
				<producer>Moldava</producer>
				<model>JU000</model>
				<date>23-01-2015</date>
				<color>GREY</color>
				<price>125.60</price>
			</good>
			<good>
				<producer>Google</producer>
				<model>GO061</model>
				<date>22-01-2015</date>
				<color>CIAN</color>
				<price>111</price>
			</good>
		</subcategory>
	</category>

	<category category_name="Electronics">
		<subcategory subcategory_name="computer">
			<good>
				<producer>Korea</producer>
				<model>RT234</model>
				<date>21-11-2014</date>
				<color>BLOND</color>
				<price>150</price>
			</good>
			<good>
				<producer>Russia</producer>
				<model>HQ225</model>
				<date>04-12-2014</date>
				<color>WHITE</color>
				<price>76</price>
			</good>
			<good>
				<producer>USA</producer>
				<model>BN777</model>
				<date>21-11-2014</date>
				<color>LIME</color>
				<price>150</price>
			</good>
			<good>
				<producer>Poland</producer>
				<model>KL555</model>
				<date>04-12-2014</date>
				<color>YELLOW</color>
				<not_in_stock />
			</good>
		</subcategory>
		<subcategory subcategory_name="phone">
			<good>
				<producer>Korea</producer>
				<model>RT234</model>
				<date>21-11-2014</date>
				<color>BLOND</color>
				<not_in_stock />
			</good>
			<good>
				<producer>Russia</producer>
				<model>HQ225</model>
				<date>04-12-2014</date>
				<color>WHITE</color>
